### ISSUE TITLE
Memory limit hit!

### ISSUE THREAD

**Issue by Status-Changer** [ycc-ustc/LUAGO#9]
I ran your code on my machine: Ubuntu 14.04 with 1GB memory and 4GB storage. However, some fatal errors about "out of memory" took place.
Could you please provide me with an estimated memory space for running this project?

**Comment by OpsNullPointerException** [comment]
I am sorry that I haven't tested it yet. I use the server at my lab, which memory is 1 TB (yeah, the memory), so that I would not be worried about the memory. But if you are concerned about it, I will do the estimation about it today and reply to you ASAP.

**Comment by Status-Changer** [comment]
> I am sorry that I haven't tested it yet. I use the server at my lab, which memory is 1 TB (yeah, the memory), so that I would not be worried about the memory. But if you are concerned about it, I will do the estimation about it today and reply to you ASAP.

Wow, that's incredible! I've never seen such a huge memory space before!
So, I really want a screenshot of your machine's memory and other device configurations to figure out whether you were in the status of sleep talking.
